<a href="https://colab.research.google.com/github/zyin36/MAT-422/blob/main/hw1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Carter Yin (zyin36)

## HW 1.2 - Linear Algebra Concepts

### 1.2.1 Linear Space (aka. Vector Space)

<i>Note: Linear space and vector space are the same thing.</i>
- **Linear Subspace** <br/>
A linear subspace a subset of vectors that is closed under vector addition and scalar multiplication.


- **How can we determine whether a vector is in a span with numpy?** <br/>

Given a vector $\mathbf{u}$ and a $\text{span}  (\mathbf{w}_1, \dots, \mathbf{w}_m)$,
if there is a solution for $x_1\mathbf{w}_1 + \dots + x_m\mathbf{w}_m = \mathbf{u}$,
then $\mathbf{u}$ is in the span, because it can be expressed as a linear combination of the vectors in the span.

The column vectors of the 3x3 identity matrix spans $\mathbb{R}_3$.



In [1]:
import numpy as np

a = np.eye(3)  # 3x3 identity matrix
b = np.array([1, 2, 3])

# linalg.solve only works if 'a' is a square and nonsingular matrix
print(np.linalg.solve(a, b))


array([1., 2., 3.])

**How to solve if the matrix (a) isn't a square matrix?**

In [5]:
# We can use least square approximation.
# If the residual is zero, then it's an exact solution
a = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1],
              [1, 0, 0]])

b = np.array([3, 1, 2, 3])

x, residuals, rank, s = np.linalg.lstsq(a, b, rcond=None)

print("Solution (x): ", x)
print("Residuals:", residuals)
print("Rank of the matrix:", rank)
print("Singular values:", s)


Solution (x):  [3. 1. 2.]
Residuals: [0.]
Rank of the matrix: 3
Singular values: [1.41421356 1.         1.        ]


### 1.2.2 Orthogonality
- Orthonormal Bases <br/>
<i> <b>Acknowledgment:</b> <br/>
Michael Albanese (https://math.stackexchange.com/users/39599/michael-albanese), Why is orthogonal basis important?, URL (version: 2014-06-12): https://math.stackexchange.com/q/518613</i>

- Best Approximation



In [8]:
def is_orthonormal_basis(basis): # the basis is defined by a matrix
  # check if all the vectors in this basis is an unit vector
  for u in basis:
    if np.linalg.norm(u) != 1.0:
      return False

  # check if two vectors are orthogonal for every pair of vectors in this basis
  length = len(basis)
  for i in range(0, length-1):
    u = basis[i]
    for j in range (i+1, length):
      v = basis[j]
      if (np.dot(u, v) != 0):
        return False

  return True

a = np.eye(3)
print(is_orthonormal_basis(a))

True


### 1.2.3 Gram-Schmidt Process

In [13]:
'''
Given a linearly independent basis a,
find an orthonormal basis of span(a).
'''
a = np.array([[5, 0, 0],
              [0, 8, 0],
              [3, 0, 3]])  # the column vectors of a is linearly independent,
                        # but not orthonormal.

a = np.transpose(a) # using column vectors

q = np.empty([3,3]) # orthonormal basis

q[0] = a[0] / np.linalg.norm(a[0]) # normalize a[0]
proj1 = np.dot(q[0], a[1]) * q[0] # proj. of a[1] onto q[0]

q[1] = (a[1] - proj1) / np.linalg.norm(a[1] - proj1)

proj2 = np.dot(q[0], a[2]) + np.dot(q[1], a[2])

q[2] = (a[2] - proj2) / np.linalg.norm(a[2] - proj2)

print(q)
print(np.linalg.norm(q[0]))
print(np.linalg.norm(q[1]))
print(np.linalg.norm(q[2]))


[[ 0.85749293  0.          0.51449576]
 [ 0.          1.          0.        ]
 [-0.5881868  -0.5881868   0.55504285]]
0.9999999999999999
1.0
1.0



### 1.2.4 Eigenvalues and Eigenvectors